### ISSUE TITLE
Milestone 0

### ISSUE THREAD

**Issue by JonahWeaver** [JonahWeaver/ScheduleMaker2#5]
- [x] Import existing data to allow manipulation
- [x] Create basic UI to represent user options and a schedule
- [ ] Reflect Majors/Minors/Schools
- [ ] Course Information Menu
- [ ] Categorize courses and majors
- [ ] Optimize data utilization and loading
